section .data
    f0          dd  0.0
    f0_1        dd  0.1
    f0_2        dd  0.2
    f0_3        dd  0.3
    f0_4        dd  0.4
    f0_5        dd  0.5
    f0_7        dd  0.7
    f0_8        dd  0.8
    f1_0        dd  1.0
    f2_0        dd  2.0
    f3_0        dd  3.0
    f5_0        dd  5.0
    f7_0        dd  7.0
    f8_0        dd  8.0
    f10_0       dd  10.0
    f16_0       dd  16.0
    f13_287     dd  13.287
    f14_69      dd  14.69
    f20_0       dd  20.0
    f21_4       dd  21.4
    f22_3       dd  22.3
    f23_2       dd  23.2
    f30_0       dd  30.0
    f40_0       dd  40.0
    f50_0       dd  50.0
    f60_0       dd  60.0
    f60_3       dd  60.3
    f70_0       dd  70.0
    f80_0       dd  80.0
    f100_0      dd  100.0
    f190_0      dd  190.0
    f200_0      dd  200.0
    f1000_0     dd  1000.0

    f_0_07      dd  -0.07
    f_0_1       dd  -0.1
    f_0_35      dd  -0.35
    f_1_1       dd  -1.1
    f_1_61      dd  -1.61
    f_59_9      dd  -59.9
    f_100_0     dd  -100
    f_1000_0    dd  -1000
    f_10000_0   dd  -10000.0

    d0_1        dq  0.1
    d0_2        dq  0.2
    d0_3        dq  0.3
    d0_4        dq  0.4
    d0_5        dq  0.5
    d0_7        dq  0.7
    d0_8        dq  0.8
    d1_0        dq  1.0
    d2_0        dq  2.0
    d10_0       dq  10.0
    d14_69      dq  14.69
    d60_3       dq  60.3
    d180_0      dq  180.0
    d300_0      dq  300.0
    d310_0      dq  310.0
    d360_0      dq  360.0
    d925_0      dq  925.0
    d1245_0     dq  1245.0

    d_1000_0    dq  -1000.0

    stt2        db  'stt2 %f',10,0
    ha0         dq  0xa0
    ;sd          db  'int: %d' , 10 , 0
    ;sdd         db  'int2: %d %d' , 10 , 0
    ;sf          db  'float: %f' , 10 , 0